options {
    directory "/var/named";
    recursion yes;
    allow-recursion { any; };
    allow-transfer { any; };
    dnssec-validation no;
    listen-on port 53 { any; };
    version "BIND";
    rate-limit {
        responses-per-second 0;
    };
};

zone "example.local" IN {
    type master;
    file "example.local.zone";
};